# Generated by Django 4.2.15 on 2024-09-01 20:00

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="language",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="language_lower_case_insensitive_unique",
                violation_error_message="Language already exists (case insensitive match)",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="language",
            field=models.ManyToManyField(
                help_text="Select a language for this book", to="catalog.language"
            ),
        ),
    ]
